name: simpnot
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://www.github.com/securearth/simpnot

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  http: ^0.13.4
